
fmod_studio_event_description_release_all_instances(vehicle_event_desc)

fmod_studio_bank_unload(master_bank_index)
fmod_studio_bank_unload(master_strings_bank_index)
fmod_studio_bank_unload(vehicles_bank_index)
