// AUTOGENERATED - DO NOT EDIT
#include <jni.h>
#include <cstddef>
#include <algorithm>
#include <string>
#include "native/GMFMODInternal_exports.h"

// JNI requires global state because the VM reference must be captured at load time.
// JNI_OnLoad() is called when the shared library is loaded; we save the JavaVM pointer
// so that native threads can attach themselves later (see ScopedEnv below).
static JavaVM* g_vm = nullptr;

// Cached Java class/method references for callbacks into GML.
// These are resolved once at init time and reused (JNI method lookups are expensive).
static jclass g_bridgeClass = nullptr;
static jmethodID g_mid_GetExtensionOption = nullptr;

// JNI_OnLoad is called automatically when System.loadLibrary() occurs.
// This is our one chance to capture the VM pointer before any other JNI calls.
extern "C" jint JNI_OnLoad(JavaVM* vm, void*) { g_vm = vm; return JNI_VERSION_1_6; }

static void throwIAE(JNIEnv* env, const char* msg) {
    jclass iae = env->FindClass("java/lang/IllegalArgumentException");
    if (iae) env->ThrowNew(iae, msg);
}

// ScopedEnv: RAII wrapper for JNIEnv* that handles thread attachment.
// Native threads that weren't created by the JVM must call AttachCurrentThread
// before making any JNI calls. This struct does it automatically in ctor,
// and DetachCurrentThread in dtor. Main thread doesn't need attach (GetEnv succeeds).
struct ScopedEnv {
    JNIEnv* env = nullptr;
    bool detach = false;

    ScopedEnv() {
        if (!g_vm) return;
        jint rc = g_vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
        if (rc == JNI_OK) return;  // Already attached (main thread case)
        if (rc == JNI_EDETACHED && g_vm->AttachCurrentThread(&env, nullptr) == JNI_OK) {
            detach = true;  // We attached, so we must detach in dtor
        } else {
            env = nullptr;  // Failed to attach
        }
    }

    ~ScopedEnv() {
        if (detach) g_vm->DetachCurrentThread();
    }
};

// UtfChars: RAII wrapper for JNI string pinning.
// GetStringUTFChars returns a temporary C-string pointer that MUST be released
// via ReleaseStringUTFChars when done. This struct ensures proper cleanup.
// Without this, we'd leak JNI local refs and potentially crash on ref table overflow.
struct UtfChars {
    JNIEnv* env; jstring s; const char* p;
    UtfChars(JNIEnv* e, jstring js) : env(e), s(js), p(js ? e->GetStringUTFChars(js, nullptr) : nullptr) {}
    ~UtfChars() { if (s && p) env->ReleaseStringUTFChars(s, p); }
    const char* c_str() const { return p; }
};

static const char* __JNI_JAVA__GetExtensionOption(const char* extName, const char* optName)
{
    thread_local std::string tls_result;
    tls_result.clear();

    ScopedEnv scoped;
    if (!g_bridgeClass || !g_mid_GetExtensionOption) {
        return nullptr;
    }

    JNIEnv* env = scoped.env;

    jstring jExtName = extName ? env->NewStringUTF(extName) : nullptr;
    jstring jOptName = optName ? env->NewStringUTF(optName) : nullptr;

    jstring jRet = static_cast<jstring>(
        env->CallStaticObjectMethod(g_bridgeClass, g_mid_GetExtensionOption, jExtName, jOptName)
    );

    if (jExtName) env->DeleteLocalRef(jExtName);
    if (jOptName) env->DeleteLocalRef(jOptName);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        if (jRet) env->DeleteLocalRef(jRet);
        return nullptr;
    }

    if (!jRet) {
        return nullptr;
    }

    const char* chars = env->GetStringUTFChars(jRet, nullptr);
    if (!chars) {
        env->DeleteLocalRef(jRet);
        return nullptr;
    }

    tls_result.assign(chars);

    env->ReleaseStringUTFChars(jRet, chars);
    env->DeleteLocalRef(jRet);

    return tls_result.c_str();
}
static void __JNI_InitExtUtils()
{
    gm::details::GMRTRunnerInterface runner{};
    runner.ExtOptGetString = __JNI_JAVA__GetExtensionOption;
    gm::ExtUtils::Init(runner);
}
// fmod_channel_set_frequency JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_set_frequency_70589B43F62C(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_set_frequency((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_get_frequency JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_get_frequency_429DD34733EE(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_get_frequency((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_set_priority JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_set_priority_F5B225C05945(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_set_priority((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_get_priority JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_get_priority_4D3DC028B0E9(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_get_priority((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_set_position JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_set_position_33E4E06A7222(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_set_position((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_get_position JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_get_position_FEC659123072(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_get_position((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_set_channel_group JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_set_channel_group_A2F6C7FFE990(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_set_channel_group((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_get_channel_group JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_get_channel_group_82B3457A6649(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_get_channel_group((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_set_loop_count JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_set_loop_count_55EB2045970E(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_set_loop_count((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_get_loop_count JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_get_loop_count_C0853F5917A6(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_get_loop_count((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_set_loop_points JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_set_loop_points_5F189AC24B7E(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_set_loop_points((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_is_virtual JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_is_virtual_A010741E6539(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_is_virtual((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_get_index JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_get_index_1A12379598C5(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_get_index((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_get_current_sound JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_get_current_sound_5984ADBF6A82(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_get_current_sound((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_channel_get_system_object JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_channel_get_system_object_D50E86E74531(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_channel_get_system_object((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_system_create JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_system_create_F3DB710D4635(JNIEnv* env, jclass /* GMFMODBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_system_create((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_system_init JNI wrapper signature: (DD)D
static jdouble __JNI_WRAPPER__fmod_system_init_830FD2A1A351(JNIEnv* /* env */, jclass /* GMFMODBridge */, jdouble max_channels, jdouble flags)
{
    double __ret = __EXT_NATIVE__fmod_system_init(static_cast<double>(max_channels), static_cast<double>(flags));
    return static_cast<jdouble>(__ret);
}

// fmod_system_release JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_system_release_9A723FAF4896(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_system_release((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_system_close JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_system_close_0F06B71DCB3F(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_system_close((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_system_update JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__fmod_system_update_1530B71DE176(JNIEnv* /* env */, jclass /* GMFMODBridge */)
{
    double __ret = __EXT_NATIVE__fmod_system_update();
    return static_cast<jdouble>(__ret);
}

// fmod_system_get_channel JNI wrapper signature: (DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_system_get_channel_C8ACB0DF0503(JNIEnv* env, jclass /* GMFMODBridge */, jdouble index, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_system_get_channel(static_cast<double>(index), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_system_get_master_channel_group JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_system_get_master_channel_group_5B394D9922DE(JNIEnv* env, jclass /* GMFMODBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_system_get_master_channel_group((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_system_set_output JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__fmod_system_set_output_301DDFFC7419(JNIEnv* /* env */, jclass /* GMFMODBridge */, jdouble output)
{
    double __ret = __EXT_NATIVE__fmod_system_set_output(static_cast<double>(output));
    return static_cast<jdouble>(__ret);
}

// fmod_system_get_output JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__fmod_system_get_output_94A3E9446A8B(JNIEnv* /* env */, jclass /* GMFMODBridge */)
{
    double __ret = __EXT_NATIVE__fmod_system_get_output();
    return static_cast<jdouble>(__ret);
}

// fmod_system_get_num_drivers JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__fmod_system_get_num_drivers_8FB5E67EB529(JNIEnv* /* env */, jclass /* GMFMODBridge */)
{
    double __ret = __EXT_NATIVE__fmod_system_get_num_drivers();
    return static_cast<jdouble>(__ret);
}

// fmod_system_set_driver JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__fmod_system_set_driver_5AB5B1A0B5BE(JNIEnv* /* env */, jclass /* GMFMODBridge */, jdouble driver)
{
    double __ret = __EXT_NATIVE__fmod_system_set_driver(static_cast<double>(driver));
    return static_cast<jdouble>(__ret);
}

// fmod_system_get_driver JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__fmod_system_get_driver_6E41EBCA4743(JNIEnv* /* env */, jclass /* GMFMODBridge */)
{
    double __ret = __EXT_NATIVE__fmod_system_get_driver();
    return static_cast<jdouble>(__ret);
}

// fmod_system_set_software_channels JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__fmod_system_set_software_channels_AF276BF953E5(JNIEnv* /* env */, jclass /* GMFMODBridge */, jdouble software_channels)
{
    double __ret = __EXT_NATIVE__fmod_system_set_software_channels(static_cast<double>(software_channels));
    return static_cast<jdouble>(__ret);
}

// fmod_system_get_software_channels JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__fmod_system_get_software_channels_73D16EEF4820(JNIEnv* /* env */, jclass /* GMFMODBridge */)
{
    double __ret = __EXT_NATIVE__fmod_system_get_software_channels();
    return static_cast<jdouble>(__ret);
}

// fmod_system_create_sound JNI wrapper signature: (Ljava/lang/String;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_system_create_sound_556A9A220B50(JNIEnv* env, jclass /* GMFMODBridge */, jstring name_or_data, jdouble mode, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_name_or_data(env, name_or_data);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_system_create_sound((char *)__pin_name_or_data.c_str(), static_cast<double>(mode), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_system_create_stream JNI wrapper signature: (Ljava/lang/String;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_system_create_stream_3450451CFE13(JNIEnv* env, jclass /* GMFMODBridge */, jstring name_or_data, jdouble mode, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_name_or_data(env, name_or_data);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_system_create_stream((char *)__pin_name_or_data.c_str(), static_cast<double>(mode), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_system_play_sound JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_system_play_sound_C47F34216BD4(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_system_play_sound((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_sound_get_length JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_sound_get_length_0F3D7E887EFD(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_sound_get_length((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_sound_set_defaults JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_sound_set_defaults_01B92843BBCA(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_sound_set_defaults((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_sound_set_mode JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_sound_set_mode_DEEAC35E7D40(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_sound_set_mode((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_sound_get_mode JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_sound_get_mode_88A3356667F1(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_sound_get_mode((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_sound_set_loop_count JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_sound_set_loop_count_D4CFA2BFEA7F(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_sound_set_loop_count((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_sound_get_loop_count JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_sound_get_loop_count_0C2403A721F9(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_sound_get_loop_count((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_sound_set_loop_points JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_sound_set_loop_points_201FCAE33F66(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_sound_set_loop_points((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_sound_set_3d_min_max_distance JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_sound_set_3d_min_max_distance_8B5EC44475B3(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_sound_set_3d_min_max_distance((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_sound_set_3d_cone_settings JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_sound_set_3d_cone_settings_8874CA129864(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_sound_set_3d_cone_settings((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_sound_release JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_sound_release_63F705F123E1(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_sound_release((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// fmod_sound_get_system_object JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__fmod_sound_get_system_object_D1B750C37CB1(JNIEnv* env, jclass /* GMFMODBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__fmod_sound_get_system_object((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// nativeRegister(Class callbackClass): cache callback + register all JNI wrappers
extern "C" {
    JNIEXPORT void JNICALL Java_com_gamemaker_ExtensionCore_ExtBridge_GMFMODBridge_nativeRegister(JNIEnv* env, jclass bridgeClass)
    {
        if (!g_bridgeClass) {
            g_bridgeClass = static_cast<jclass>(env->NewGlobalRef(bridgeClass));
        }

        if (!g_mid_GetExtensionOption) {
            g_mid_GetExtensionOption = env->GetStaticMethodID(
                g_bridgeClass,
                "__EXT_JAVA__GetExtensionOption",
                "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"
            );
            if (!g_mid_GetExtensionOption) {
                throwIAE(env, "Failed to bind __EXT_JAVA__GetExtensionOption");
                return;
            }
        }

        static bool g_extUtilsInitialized = false;
        if (!g_extUtilsInitialized) {
            __JNI_InitExtUtils();
            g_extUtilsInitialized = true;
        }

        // Registers all the native methods
        static const JNINativeMethod methods[] = {
            { "__EXT_JNI__fmod_channel_set_frequency", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_set_frequency_70589B43F62C },
            { "__EXT_JNI__fmod_channel_get_frequency", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_get_frequency_429DD34733EE },
            { "__EXT_JNI__fmod_channel_set_priority", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_set_priority_F5B225C05945 },
            { "__EXT_JNI__fmod_channel_get_priority", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_get_priority_4D3DC028B0E9 },
            { "__EXT_JNI__fmod_channel_set_position", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_set_position_33E4E06A7222 },
            { "__EXT_JNI__fmod_channel_get_position", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_get_position_FEC659123072 },
            { "__EXT_JNI__fmod_channel_set_channel_group", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_set_channel_group_A2F6C7FFE990 },
            { "__EXT_JNI__fmod_channel_get_channel_group", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_get_channel_group_82B3457A6649 },
            { "__EXT_JNI__fmod_channel_set_loop_count", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_set_loop_count_55EB2045970E },
            { "__EXT_JNI__fmod_channel_get_loop_count", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_get_loop_count_C0853F5917A6 },
            { "__EXT_JNI__fmod_channel_set_loop_points", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_set_loop_points_5F189AC24B7E },
            { "__EXT_JNI__fmod_channel_is_virtual", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_is_virtual_A010741E6539 },
            { "__EXT_JNI__fmod_channel_get_index", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_get_index_1A12379598C5 },
            { "__EXT_JNI__fmod_channel_get_current_sound", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_get_current_sound_5984ADBF6A82 },
            { "__EXT_JNI__fmod_channel_get_system_object", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_channel_get_system_object_D50E86E74531 },
            { "__EXT_JNI__fmod_system_create", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_system_create_F3DB710D4635 },
            { "__EXT_JNI__fmod_system_init", "(DD)D", (void*)__JNI_WRAPPER__fmod_system_init_830FD2A1A351 },
            { "__EXT_JNI__fmod_system_release", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_system_release_9A723FAF4896 },
            { "__EXT_JNI__fmod_system_close", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_system_close_0F06B71DCB3F },
            { "__EXT_JNI__fmod_system_update", "()D", (void*)__JNI_WRAPPER__fmod_system_update_1530B71DE176 },
            { "__EXT_JNI__fmod_system_get_channel", "(DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_system_get_channel_C8ACB0DF0503 },
            { "__EXT_JNI__fmod_system_get_master_channel_group", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_system_get_master_channel_group_5B394D9922DE },
            { "__EXT_JNI__fmod_system_set_output", "(D)D", (void*)__JNI_WRAPPER__fmod_system_set_output_301DDFFC7419 },
            { "__EXT_JNI__fmod_system_get_output", "()D", (void*)__JNI_WRAPPER__fmod_system_get_output_94A3E9446A8B },
            { "__EXT_JNI__fmod_system_get_num_drivers", "()D", (void*)__JNI_WRAPPER__fmod_system_get_num_drivers_8FB5E67EB529 },
            { "__EXT_JNI__fmod_system_set_driver", "(D)D", (void*)__JNI_WRAPPER__fmod_system_set_driver_5AB5B1A0B5BE },
            { "__EXT_JNI__fmod_system_get_driver", "()D", (void*)__JNI_WRAPPER__fmod_system_get_driver_6E41EBCA4743 },
            { "__EXT_JNI__fmod_system_set_software_channels", "(D)D", (void*)__JNI_WRAPPER__fmod_system_set_software_channels_AF276BF953E5 },
            { "__EXT_JNI__fmod_system_get_software_channels", "()D", (void*)__JNI_WRAPPER__fmod_system_get_software_channels_73D16EEF4820 },
            { "__EXT_JNI__fmod_system_create_sound", "(Ljava/lang/String;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_system_create_sound_556A9A220B50 },
            { "__EXT_JNI__fmod_system_create_stream", "(Ljava/lang/String;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_system_create_stream_3450451CFE13 },
            { "__EXT_JNI__fmod_system_play_sound", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_system_play_sound_C47F34216BD4 },
            { "__EXT_JNI__fmod_sound_get_length", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_sound_get_length_0F3D7E887EFD },
            { "__EXT_JNI__fmod_sound_set_defaults", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_sound_set_defaults_01B92843BBCA },
            { "__EXT_JNI__fmod_sound_set_mode", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_sound_set_mode_DEEAC35E7D40 },
            { "__EXT_JNI__fmod_sound_get_mode", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_sound_get_mode_88A3356667F1 },
            { "__EXT_JNI__fmod_sound_set_loop_count", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_sound_set_loop_count_D4CFA2BFEA7F },
            { "__EXT_JNI__fmod_sound_get_loop_count", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_sound_get_loop_count_0C2403A721F9 },
            { "__EXT_JNI__fmod_sound_set_loop_points", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_sound_set_loop_points_201FCAE33F66 },
            { "__EXT_JNI__fmod_sound_set_3d_min_max_distance", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_sound_set_3d_min_max_distance_8B5EC44475B3 },
            { "__EXT_JNI__fmod_sound_set_3d_cone_settings", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_sound_set_3d_cone_settings_8874CA129864 },
            { "__EXT_JNI__fmod_sound_release", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_sound_release_63F705F123E1 },
            { "__EXT_JNI__fmod_sound_get_system_object", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__fmod_sound_get_system_object_D1B750C37CB1 },
        };

        env->RegisterNatives(bridgeClass, methods, sizeof(methods)/sizeof(methods[0]));
    }
}
