package com.gamemaker.ExtensionCore.ExtBridge;
import java.lang.String;
import java.nio.ByteBuffer;
import ${YYAndroidPackageName}.GMExtUtils;

public final class GMFMODBridge {
    static {
        // this is the extension lib name
        System.loadLibrary("GMFMOD");
        nativeRegister();
    }
    // this registers the native functions on the C++ layer
    private static native void nativeRegister();

    public static String __EXT_JAVA__GetExtensionOption(String extName, String optName)
    {
        return GMExtUtils.GetExtensionOption(extName, optName);
    }

    public static native double __EXT_JNI__GMFMOD_invocation_handler(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__GMFMOD_queue_buffer(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_last_result(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_debug_initialize(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_path_bundle(String filename);
    public static native String __EXT_JNI__fmod_path_user(String filename);
    public static native String __EXT_JNI__fmod_error_string(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_set_frequency(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_get_frequency(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_set_priority(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_get_priority(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_set_position(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_get_position(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_set_channel_group(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_get_channel_group(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_channel_set_loop_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_get_loop_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_set_loop_points(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_is_virtual(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_get_index(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_get_current_sound(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_channel_get_system_object(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_create(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_init(double max_channels, double flags);
    public static native double __EXT_JNI__fmod_system_release(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_system_close(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_system_update();
    public static native double __EXT_JNI__fmod_system_get_channels_playing();
    public static native double __EXT_JNI__fmod_system_get_channel(double index, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_get_master_channel_group(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_set_output(double output);
    public static native double __EXT_JNI__fmod_system_get_output();
    public static native double __EXT_JNI__fmod_system_get_num_drivers();
    public static native double __EXT_JNI__fmod_system_set_driver(double driver);
    public static native double __EXT_JNI__fmod_system_get_driver();
    public static native double __EXT_JNI__fmod_system_set_software_channels(double software_channels);
    public static native double __EXT_JNI__fmod_system_get_software_channels();
    public static native double __EXT_JNI__fmod_system_set_3d_settings(double doppler_scale, double distance_factor, double rolloff_scale);
    public static native double __EXT_JNI__fmod_system_get_3d_settings(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_set_3d_listener_attributes(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_system_get_3d_listener_attributes(double listener_index, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_get_record_num_drivers();
    public static native double __EXT_JNI__fmod_system_get_record_driver_info(double record_driver_index, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_get_record_position(double device_index);
    public static native double __EXT_JNI__fmod_system_record_start(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_system_record_stop(double device_index);
    public static native double __EXT_JNI__fmod_system_is_recording(double device_index);
    public static native double __EXT_JNI__fmod_system_create_dsp(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_create_dsp_by_type(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_get_dsp_buffer_size(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_set_dsp_buffer_size(double buff_size, double num_buffers);
    public static native double __EXT_JNI__fmod_system_get_software_format(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_set_software_format(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_system_set_stream_buffer_size(double file_buffer_size, double file_buffer_size_type);
    public static native double __EXT_JNI__fmod_system_get_driver_info(double driver_id, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_create_channel_group(String name, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_play_dsp(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_select(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_system_create_sound(String name_or_data, double mode, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_create_stream(String name_or_data, double mode, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_system_play_sound(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_length(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_set_defaults(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_set_mode(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_mode(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_format(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_sound_get_name(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_defaults(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_set_loop_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_loop_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_set_loop_points(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_loop_points(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_set_3d_min_max_distance(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_3d_min_max_distance(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_set_3d_cone_settings(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_3d_cone_settings(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_set_3d_custom_rolloff(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_3d_custom_rolloff(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_num_sync_points(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_sync_point(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_add_sync_point(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_delete_sync_point(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_music_num_channels(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_set_music_channel_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_music_channel_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_set_music_speed(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_music_speed(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_set_sound_group(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_sound_group(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_release(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_system_object(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_open_state(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_tag(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_num_sub_sounds(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_get_sub_sound(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_read_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_group_get_num_channels(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_group_get_channel(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_channel_group_add_group(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_channel_group_get_num_groups(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_group_get_group(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_channel_group_get_parent_group(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native String __EXT_JNI__fmod_channel_group_get_name(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_group_release(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_group_get_system_object(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_set_max_audible(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_get_max_audible(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_set_max_audible_behavior(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_get_max_audible_behavior(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_set_mute_fade_speed(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_get_mute_fade_speed(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_set_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_get_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_get_num_sounds(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_get_sound(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_get_num_playing(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_stop(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_sound_group_get_name(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_release(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_sound_group_get_system_object(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_reverb_3d_set_active(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_reverb_3d_get_active(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_reverb_3d_set_properties(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_reverb_3d_release(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_is_playing(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_stop(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_mode(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_mode(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_pitch(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_pitch(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_audibility(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_volume_ramp(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_volume_ramp(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_mute(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_mute(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_3d_doppler_level(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_3d_doppler_level(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_3d_level(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_3d_level(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_3d_min_max_distance(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_3d_cone_settings(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_3d_occlusion(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_3d_attributes(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_3d_attributes(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_3d_spread(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_3d_spread(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_3d_distance_filter(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_pan(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_mix_levels_output(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_reverb_properties(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_reverb_properties(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_low_pass_gain(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_low_pass_gain(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_add_dsp(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_remove_dsp(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_num_dsps(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_dsp(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_dsp_index(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_dsp_index(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_system_object(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_delay(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_delay(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_get_dsp_clock(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_channel_control_set_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_add_input(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_num_inputs(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_num_outputs(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_disconnect_all(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_num_parameters(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_set_parameter_float(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_parameter_float(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_set_parameter_int(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_parameter_int(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_set_parameter_bool(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_parameter_bool(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_release(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_system_object(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_input(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_output(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_disconnect_from(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_data_parameter_index(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_set_parameter_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_parameter_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_parameter_info(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_set_channel_format(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_channel_format(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_output_channel_format(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_metering_info(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_set_metering_enabled(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_metering_enabled(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_set_active(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_active(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_set_bypass(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_bypass(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_set_wet_dry_mix(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_wet_dry_mix(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_idle(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_reset(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_type(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_info(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_cpu_usage(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_set_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_get_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_set_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_connection_set_mix(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_connection_get_mix(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_connection_set_mix_matrix(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_connection_get_mix_matrix(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_connection_get_input(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_connection_get_output(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_connection_get_type(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_connection_set_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_dsp_connection_get_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_geometry_set_polygon_attributes(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_geometry_get_polygon_num_vertices(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_geometry_set_position(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_geometry_set_rotation(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_geometry_set_scale(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_geometry_save(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_geometry_release(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_create(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_init(double max_channels, double studio_flags, double core_flags);
    public static native double __EXT_JNI__fmod_studio_system_release();
    public static native double __EXT_JNI__fmod_studio_system_update();
    public static native double __EXT_JNI__fmod_studio_system_flush_commands();
    public static native double __EXT_JNI__fmod_studio_system_flush_sample_loading();
    public static native double __EXT_JNI__fmod_studio_system_load_bank_file(String filename, double flags, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_load_bank_memory(String data, double flags, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_unload_all();
    public static native double __EXT_JNI__fmod_studio_system_get_bank_count();
    public static native double __EXT_JNI__fmod_studio_system_get_bank_at(double index, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_bank(String path, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_event(String path, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_create_event_instance(String path, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_bus(String path, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_master_bus(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_vca(String path, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_set_listener_attributes(double listener_index, double x, double y, double z);
    public static native double __EXT_JNI__fmod_studio_system_set_listener_weight(double listener_index, double weight);
    public static native double __EXT_JNI__fmod_studio_system_set_parameter_by_name(String name, double value);
    public static native double __EXT_JNI__fmod_studio_system_get_parameter_by_name(String name);
    public static native double __EXT_JNI__fmod_studio_system_get_core_system(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_set_num_listeners(double count);
    public static native String __EXT_JNI__fmod_studio_system_lookup_id(String path);
    public static native double __EXT_JNI__fmod_studio_system_get_event_by_id(String id, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_start_command_capture(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_stop_command_capture();
    public static native double __EXT_JNI__fmod_studio_system_load_command_replay(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_unload(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_loading_state(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_sample_loading_state(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_studio_bank_get_path(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_parent_studio_system(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_event_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_event_at(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_bus_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_bus_at(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_vca_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_vca_at(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_string_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_studio_event_description_get_path(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_create_instance(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_instance_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_instance_at(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_is_snapshot(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_is_one_shot(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_has_sustain_point(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_length(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_parameter_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_release_all_instances(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_parameter_description_by_name(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_load_sample_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_start(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_stop(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_playback_state(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_timeline_position(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_timeline_position(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_pitch(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_pitch(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_parameter_by_name(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_parameter_by_name(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_parameter_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_parameter_by_id(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_parameter_by_id(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_3d_attributes(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_description(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_release(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_studio_bus_get_path(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_get_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_set_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_get_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_set_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_stop_all_events(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_get_master_bus(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native String __EXT_JNI__fmod_studio_vca_get_path(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_vca_get_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_vca_set_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_playback_state(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_current_command(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_release(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_command_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_length(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_set_frame_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_set_create_instance_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_set_load_bank_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
}