package com.ACOMPANY.APROJECT;
import java.nio.ByteBuffer;
public class MainActivity {

	public static native double JNIfmodchannelsetfrequency(double arg0,double arg1);
	public static native double JNIfmodchannelgetfrequency(double arg0);
	public static native double JNIfmodchannelsetpriority(double arg0,double arg1);
	public static native double JNIfmodchannelgetpriority(double arg0);
	public static native double JNIfmodchannelsetposition(double arg0,double arg1,double arg2);
	public static native double JNIfmodchannelgetposition(double arg0,double arg1);
	public static native double JNIfmodchannelsetchannelgroup(double arg0,double arg1);
	public static native double JNIfmodchannelgetchannelgroup(double arg0);
	public static native double JNIfmodchannelsetloopcount(double arg0,double arg1);
	public static native double JNIfmodchannelgetloopcount(double arg0);
	public static native double JNIfmodchannelsetlooppoints(double arg0,double arg1,double arg2,double arg3,double arg4);
	public static native double JNIfmodchannelgetlooppointsmultiplatform(double arg0,double arg1,double arg2,ByteBuffer arg3);
	public static native double JNIfmodchannelisvirtual(double arg0);
	public static native double JNIfmodchannelgetcurrentsound(double arg0);
	public static native double JNIfmodchannelgetindex(double arg0);
	public static native double JNIfmodchannelgetsystemobject(double arg0);
	public static native double JNIfmodchannelcontrolisplaying(double arg0);
	public static native double JNIfmodchannelcontrolstop(double arg0);
	public static native double JNIfmodchannelcontrolsetpaused(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolgetpaused(double arg0);
	public static native double JNIfmodchannelcontrolsetmode(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolgetmode(double arg0);
	public static native double JNIfmodchannelcontrolsetpitch(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolgetpitch(double arg0);
	public static native double JNIfmodchannelcontrolgetaudibility(double arg0);
	public static native double JNIfmodchannelcontrolsetvolume(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolgetvolume(double arg0);
	public static native double JNIfmodchannelcontrolsetvolumeramp(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolgetvolumeramp(double arg0);
	public static native double JNIfmodchannelcontrolsetmute(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolgetmute(double arg0);
	public static native double JNIfmodchannelcontrolset3dattributesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolget3dattributesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolset3dconeorientationmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolget3dconeorientationmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolset3dconesettings(double arg0,double arg1,double arg2,double arg3);
	public static native double JNIfmodchannelcontrolget3dconesettingsmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolset3dcustomrolloffmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolget3dcustomrolloffmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolset3ddistancefilter(double arg0,double arg1,double arg2,double arg3);
	public static native double JNIfmodchannelcontrolget3ddistancefiltermultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolset3ddopplerlevel(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolget3ddopplerlevel(double arg0);
	public static native double JNIfmodchannelcontrolset3dlevel(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolget3dlevel(double arg0);
	public static native double JNIfmodchannelcontrolset3dminmaxdistance(double arg0,double arg1,double arg2);
	public static native double JNIfmodchannelcontrolget3dminmaxdistancemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolset3docclusion(double arg0,double arg1,double arg2);
	public static native double JNIfmodchannelcontrolget3docclusionmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolset3dspread(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolget3dspread(double arg0);
	public static native double JNIfmodchannelcontrolsetpan(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolsetmixlevelsinputmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolsetmixlevelsoutput(double arg0,double arg1,double arg2,double arg3,double arg4,double arg5,double arg6,double arg7,double arg8);
	public static native double JNIfmodchannelcontrolsetmixmatrixmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolgetmixmatrixmultiplatform(double arg0,double arg1,ByteBuffer arg2);
	public static native double JNIfmodchannelcontrolsetreverbproperties(double arg0,double arg1,double arg2);
	public static native double JNIfmodchannelcontrolgetreverbproperties(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolsetlowpassgain(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolgetlowpassgain(double arg0);
	public static native double JNIfmodchannelcontroladddsp(double arg0,double arg1,double arg2);
	public static native double JNIfmodchannelcontrolremovedsp(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolgetnumdsps(double arg0);
	public static native double JNIfmodchannelcontrolgetdsp(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolsetdspindex(double arg0,double arg1,double arg2);
	public static native double JNIfmodchannelcontrolgetdspindex(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolgetdspclockmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolsetdelaymultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolgetdelaymultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontroladdfadepointmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolsetfadepointrampmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolremovefadepointsmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolgetfadepointsmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodchannelcontrolsetcallback(double arg0);
	public static native double JNIfmodchannelcontrolgetsystemobject(double arg0);
	public static native double JNIfmodchannelcontrolsetuserdata(double arg0,double arg1);
	public static native double JNIfmodchannelcontrolgetuserdata(double arg0);
	public static native double JNIfmodchannelgroupgetnumchannels(double arg0);
	public static native double JNIfmodchannelgroupgetchannel(double arg0,double arg1);
	public static native double JNIfmodchannelgroupaddgroupmultiplatform(double arg0,double arg1,double arg2);
	public static native double JNIfmodchannelgroupgetnumgroups(double arg0);
	public static native double JNIfmodchannelgroupgetgroup(double arg0,double arg1);
	public static native double JNIfmodchannelgroupgetparentgroup(double arg0);
	public static native String JNIfmodchannelgroupgetname(double arg0);
	public static native double JNIfmodchannelgrouprelease(double arg0);
	public static native double JNIfmodchannelgroupgetsystemobject(double arg0);
	public static native double JNIfmodfilegetdiskbusy();
	public static native double JNIfmodfilesetdiskbusy(double arg0);
	public static native double JNIfmodmemorygetstatsmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmoddebuginitializemultiplatform(double arg0,double arg1,String arg2);
	public static native double JNIfmodthreadsetattributes(double arg0,double arg1,double arg2,double arg3);
	public static native double JNIfmoddspaddinputmultiplatform(double arg0,double arg1,double arg2);
	public static native double JNIfmoddspgetinputmultiplatform(double arg0,double arg1,ByteBuffer arg2);
	public static native double JNIfmoddspgetoutputmultiplatform(double arg0,double arg1,ByteBuffer arg2);
	public static native double JNIfmoddspgetnuminputs(double arg0);
	public static native double JNIfmoddspgetnumoutputs(double arg0);
	public static native double JNIfmoddspdisconnectall(double arg0,double arg1,double arg2);
	public static native double JNIfmoddspdisconnectfrommutliplatform(double arg0,double arg1,double arg2);
	public static native double JNIfmoddspgetdataparameterindex(double arg0,double arg1);
	public static native double JNIfmoddspgetnumparameters(double arg0);
	public static native double JNIfmoddspsetparameterbool(double arg0,double arg1,double arg2);
	public static native double JNIfmoddspgetparameterbool(double arg0,double arg1);
	public static native double JNIfmoddspsetparameterdatamultiplatform(double arg0,double arg1,ByteBuffer arg2,double arg3);
	public static native double JNIfmoddspgetparameterdatamultiplatform(double arg0,double arg1,ByteBuffer arg2,double arg3);
	public static native double JNIfmoddspsetparameterfloat(double arg0,double arg1,double arg2);
	public static native double JNIfmoddspgetparameterfloat(double arg0,double arg1);
	public static native double JNIfmoddspsetparameterint(double arg0,double arg1,double arg2);
	public static native double JNIfmoddspgetparameterint(double arg0,double arg1);
	public static native double JNIfmoddspgetparameterinfomultiplatform(double arg0,double arg1,ByteBuffer arg2);
	public static native double JNIfmoddspsetchannelformat(double arg0,double arg1,double arg2,double arg3);
	public static native double JNIfmoddspgetchannelformatmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmoddspgetoutputchannelformatmultiplatform(double arg0,ByteBuffer arg1,ByteBuffer arg2);
	public static native double JNIfmoddspgetmeteringinfomultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmoddspsetmeteringenabled(double arg0,double arg1,double arg2);
	public static native double JNIfmoddspgetmeteringenabledmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmoddspsetactive(double arg0,double arg1);
	public static native double JNIfmoddspgetactive(double arg0);
	public static native double JNIfmoddspsetbypass(double arg0,double arg1);
	public static native double JNIfmoddspgetbypass(double arg0);
	public static native double JNIfmoddspsetwetdrymix(double arg0,double arg1,double arg2,double arg3);
	public static native double JNIfmoddspgetwetdrymixmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmoddspgetidle(double arg0);
	public static native double JNIfmoddspreset(double arg0);
	public static native double JNIfmoddsprelease(double arg0);
	public static native double JNIfmoddspgettype(double arg0);
	public static native double JNIfmoddspgetinfomultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmoddspgetcpuusagemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmoddspsetuserdata(double arg0,double arg1);
	public static native double JNIfmoddspgetuserdata(double arg0);
	public static native double JNIfmoddspsetcallback(double arg0);
	public static native double JNIfmoddspgetsystemobject(double arg0);
	public static native double JNIfmoddspconnectionsetmix(double arg0,double arg1);
	public static native double JNIfmoddspconnectiongetmix(double arg0);
	public static native double JNIfmoddspconnectionsetmixmatrixmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmoddspconnectiongetmixmatrixmultiplatform(double arg0,double arg1,ByteBuffer arg2);
	public static native double JNIfmoddspconnectiongetinput(double arg0);
	public static native double JNIfmoddspconnectiongetoutput(double arg0);
	public static native double JNIfmoddspconnectiongettype(double arg0);
	public static native double JNIfmoddspconnectionsetuserdata(double arg0,double arg1);
	public static native double JNIfmoddspconnectiongetuserdata(double arg0);
	public static native double JNIfmodgeometrysetpolygonattributes(double arg0,double arg1,double arg2,double arg3,double arg4);
	public static native double JNIfmodgeometrygetpolygonattributesmultiplatform(double arg0,double arg1,ByteBuffer arg2);
	public static native double JNIfmodgeometrygetpolygonnumvertices(double arg0,double arg1);
	public static native double JNIfmodgeometrysetpolygonvertexmultiplatform(double arg0,double arg1,double arg2,ByteBuffer arg3);
	public static native double JNIfmodgeometrygetpolygonvertexmultiplatform(double arg0,double arg1,double arg2,ByteBuffer arg3);
	public static native double JNIfmodgeometrysetpositionmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodgeometrygetpositionmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodgeometrysetrotationmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodgeometrygetrotationmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodgeometrysetscalemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodgeometrygetscalemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodgeometryaddpolygonmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodgeometrysetactive(double arg0,double arg1);
	public static native double JNIfmodgeometrygetactive(double arg0);
	public static native double JNIfmodgeometrygetmaxpolygonsmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodgeometrygetnumpolygons(double arg0);
	public static native double JNIfmodgeometrysetuserdata(double arg0,double arg1);
	public static native double JNIfmodgeometrygetuserdata(double arg0);
	public static native double JNIfmodgeometryrelease(double arg0);
	public static native double JNIfmodgeometrysavemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodreverb3dset3dattributesmultiplatform(double arg0,ByteBuffer arg1,double arg2,double arg3);
	public static native double JNIfmodreverb3dget3dattributesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodreverb3dsetproperties(double arg0,double arg1,double arg2,double arg3,double arg4,double arg5,double arg6,double arg7,double arg8,double arg9,double arg10,double arg11,double arg12);
	public static native double JNIfmodreverb3dgetpropertiesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodreverb3dsetactive(double arg0,double arg1);
	public static native double JNIfmodreverb3dgetactive(double arg0);
	public static native double JNIfmodreverb3drelease(double arg0);
	public static native double JNIfmodreverb3dsetuserdata(double arg0,double arg1);
	public static native double JNIfmodreverb3dgetuserdata(double arg0);
	public static native String JNIfmodsoundgetname(double arg0);
	public static native double JNIfmodsoundgetformatmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsoundgetlength(double arg0,double arg1);
	public static native double JNIfmodsoundgetnumtagsmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsoundgettagmultiplatform(double arg0,double arg1,ByteBuffer arg2,ByteBuffer arg3);
	public static native double JNIfmodsoundset3dconesettings(double arg0,double arg1,double arg2,double arg3);
	public static native double JNIfmodsoundget3dconesettingsmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsoundset3dcustomrolloffmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsoundget3dcustomrolloffmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsoundset3dminmaxdistance(double arg0,double arg1,double arg2);
	public static native double JNIfmodsoundget3dminmaxdistancemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsoundsetdefaults(double arg0,double arg1,double arg2);
	public static native double JNIfmodsoundgetdefaultsmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsoundsetmode(double arg0,double arg1);
	public static native double JNIfmodsoundgetmode(double arg0);
	public static native double JNIfmodsoundsetloopcount(double arg0,double arg1);
	public static native double JNIfmodsoundgetloopcount(double arg0);
	public static native double JNIfmodsoundsetlooppoints(double arg0,double arg1,double arg2,double arg3,double arg4);
	public static native double JNIfmodsoundgetlooppointsmultiplatform(double arg0,double arg1,double arg2,ByteBuffer arg3);
	public static native double JNIfmodsoundsetsoundgroup(double arg0,double arg1);
	public static native double JNIfmodsoundgetsoundgroup(double arg0);
	public static native double JNIfmodsoundgetnumsubsounds(double arg0);
	public static native double JNIfmodsoundgetsubsound(double arg0,double arg1);
	public static native double JNIfmodsoundgetsubsoundparent(double arg0);
	public static native double JNIfmodsoundgetopenstatemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsoundreaddatamultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsoundseekdata(double arg0,double arg1);
	public static native double JNIfmodsoundlockmultiplatform(double arg0,ByteBuffer arg1,ByteBuffer arg2);
	public static native double JNIfmodsoundunlockmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsoundgetmusicnumchannels(double arg0);
	public static native double JNIfmodsoundsetmusicchannelvolume(double arg0,double arg1,double arg2);
	public static native double JNIfmodsoundgetmusicchannelvolume(double arg0,double arg1);
	public static native double JNIfmodsoundsetmusicspeed(double arg0,double arg1);
	public static native double JNIfmodsoundgetmusicspeed(double arg0);
	public static native double JNIfmodsoundgetsyncpointmultiplatform(double arg0,double arg1,double arg2,ByteBuffer arg3);
	public static native double JNIfmodsoundgetnumsyncpoints(double arg0);
	public static native double JNIfmodsoundaddsyncpoint(double arg0,double arg1,double arg2,String arg3);
	public static native double JNIfmodsounddeletesyncpoint(double arg0,double arg1);
	public static native double JNIfmodsoundrelease(double arg0);
	public static native double JNIfmodsoundgetsystemobject(double arg0);
	public static native double JNIfmodsoundsetuserdata(double arg0,double arg1);
	public static native double JNIfmodsoundgetuserdata(double arg0);
	public static native double JNIfmodsoundgroupsetmaxaudible(double arg0,double arg1);
	public static native double JNIfmodsoundgroupgetmaxaudible(double arg0);
	public static native double JNIfmodsoundgroupsetmaxaudiblebehavior(double arg0,double arg1);
	public static native double JNIfmodsoundgroupgetmaxaudiblebehavior(double arg0);
	public static native double JNIfmodsoundgroupsetmutefadespeed(double arg0,double arg1);
	public static native double JNIfmodsoundgroupgetmutefadespeed(double arg0);
	public static native double JNIfmodsoundgroupsetvolume(double arg0,double arg1);
	public static native double JNIfmodsoundgroupgetvolume(double arg0);
	public static native double JNIfmodsoundgroupgetnumsounds(double arg0);
	public static native double JNIfmodsoundgroupgetsound(double arg0,double arg1);
	public static native double JNIfmodsoundgroupgetnumplaying(double arg0);
	public static native double JNIfmodsoundgroupstop(double arg0);
	public static native String JNIfmodsoundgroupgetname(double arg0);
	public static native double JNIfmodsoundgrouprelease(double arg0);
	public static native double JNIfmodsoundgroupgetsystemobject(double arg0);
	public static native double JNIfmodsoundgroupsetuserdata(double arg0,double arg1);
	public static native double JNIfmodsoundgroupgetuserdata(double arg0);
	public static native double JNIfmodstudiobankgetloadingstate(double arg0);
	public static native double JNIfmodstudiobankloadsampledata(double arg0);
	public static native double JNIfmodstudiobankunloadsampledata(double arg0);
	public static native double JNIfmodstudiobankgetsampleloadingstate(double arg0);
	public static native double JNIfmodstudiobankunload(double arg0);
	public static native double JNIfmodstudiobankgetbuscount(double arg0);
	public static native double JNIfmodstudiobankgetbuslistmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiobankgeteventcount(double arg0);
	public static native double JNIfmodstudiobankgeteventdescriptionlistmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiobankgetstringcount(double arg0);
	public static native double JNIfmodstudiobankgetstringinfomultiplatform(double arg0,double arg1,ByteBuffer arg2);
	public static native double JNIfmodstudiobankgetvcacount(double arg0);
	public static native double JNIfmodstudiobankgetvcalistmultiplatform(double arg0,ByteBuffer arg1);
	public static native String JNIfmodstudiobankgetid(double arg0);
	public static native String JNIfmodstudiobankgetpath(double arg0);
	public static native double JNIfmodstudiobankisvalid(double arg0);
	public static native double JNIfmodstudiobanksetuserdata(double arg0,double arg1);
	public static native double JNIfmodstudiobankgetuserdata(double arg0);
	public static native double JNIfmodstudiobussetpaused(double arg0,double arg1);
	public static native double JNIfmodstudiobusgetpaused(double arg0);
	public static native double JNIfmodstudiobusstopallevents(double arg0,double arg1);
	public static native double JNIfmodstudiobussetvolume(double arg0,double arg1);
	public static native double JNIfmodstudiobusgetvolume(double arg0);
	public static native double JNIfmodstudiobussetmute(double arg0,double arg1);
	public static native double JNIfmodstudiobusgetmute(double arg0);
	public static native double JNIfmodstudiobussetportindexmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiobusgetportindexmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiobusgetchannelgroup(double arg0);
	public static native double JNIfmodstudiobuslockchannelgroup(double arg0);
	public static native double JNIfmodstudiobusunlockchannelgroup(double arg0);
	public static native double JNIfmodstudiobusgetcpuusagemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiobusgetmemoryusagemultiplatform(double arg0,ByteBuffer arg1);
	public static native String JNIfmodstudiobusgetid(double arg0);
	public static native String JNIfmodstudiobusgetpath(double arg0);
	public static native double JNIfmodstudiobusisvalid(double arg0);
	public static native double JNIfmodstudiocommandreplaysetbankpath(double arg0,String arg1);
	public static native double JNIfmodstudiocommandreplaysetcreateinstancecallback(double arg0);
	public static native double JNIfmodstudiocommandreplaysetframecallback(double arg0);
	public static native double JNIfmodstudiocommandreplaysetloadbankcallback(double arg0,String arg1);
	public static native double JNIfmodstudiocommandreplaystart(double arg0);
	public static native double JNIfmodstudiocommandreplaystop(double arg0);
	public static native double JNIfmodstudiocommandreplaygetcurrentcommandmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiocommandreplaygetplaybackstate(double arg0);
	public static native double JNIfmodstudiocommandreplaysetpaused(double arg0,double arg1);
	public static native double JNIfmodstudiocommandreplaygetpaused(double arg0);
	public static native double JNIfmodstudiocommandreplayseektocommand(double arg0,double arg1);
	public static native double JNIfmodstudiocommandreplayseektotime(double arg0,double arg1);
	public static native double JNIfmodstudiocommandreplaygetcommandattime(double arg0,double arg1);
	public static native double JNIfmodstudiocommandreplaygetcommandcount(double arg0);
	public static native double JNIfmodstudiocommandreplaygetcommandinfomultiplatform(double arg0,double arg1,ByteBuffer arg2);
	public static native String JNIfmodstudiocommandreplaygetcommandstring(double arg0,double arg1);
	public static native double JNIfmodstudiocommandreplaygetlength(double arg0);
	public static native double JNIfmodstudiocommandreplaygetsystemobject(double arg0);
	public static native double JNIfmodstudiocommandreplayisvalid(double arg0);
	public static native double JNIfmodstudiocommandreplaysetuserdata(double arg0,double arg1);
	public static native double JNIfmodstudiocommandreplaygetuserdata(double arg0);
	public static native double JNIfmodstudiocommandreplayrelease(double arg0);
	public static native double JNIfmodstudioeventdescriptioncreateinstance(double arg0);
	public static native double JNIfmodstudioeventdescriptiongetinstancecount(double arg0);
	public static native double JNIfmodstudioeventdescriptiongetinstancelistmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudioeventdescriptionreleaseallinstances(double arg0);
	public static native double JNIfmodstudioeventdescriptionloadsampledata(double arg0);
	public static native double JNIfmodstudioeventdescriptionunloadsampledata(double arg0);
	public static native double JNIfmodstudioeventdescriptiongetsampleloadingstate(double arg0);
	public static native double JNIfmodstudioeventdescriptionis3d(double arg0);
	public static native double JNIfmodstudioeventdescriptionisdopplerenabled(double arg0);
	public static native double JNIfmodstudioeventdescriptionisoneshot(double arg0);
	public static native double JNIfmodstudioeventdescriptionissnapshot(double arg0);
	public static native double JNIfmodstudioeventdescriptionisstream(double arg0);
	public static native double JNIfmodstudioeventdescriptionhassustainpoint(double arg0);
	public static native double JNIfmodstudioeventdescriptiongetminmaxdistancemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudioeventdescriptiongetsoundsize(double arg0);
	public static native double JNIfmodstudioeventdescriptiongetparameterdescriptionbynamemultiplatform(double arg0,String arg1,ByteBuffer arg2);
	public static native double JNIfmodstudioeventdescriptiongetparameterdescriptionbyidmultiplatform(double arg0,ByteBuffer arg1,ByteBuffer arg2);
	public static native double JNIfmodstudioeventdescriptiongetparameterdescriptionbyindexmultiplatform(double arg0,double arg1,ByteBuffer arg2);
	public static native double JNIfmodstudioeventdescriptiongetparameterdescriptioncount(double arg0);
	public static native String JNIfmodstudioeventdescriptiongetparameterlabelbyname(double arg0,String arg1,double arg2);
	public static native String JNIfmodstudioeventdescriptiongetparameterlabelbyidmultiplatform(double arg0,ByteBuffer arg1,double arg2);
	public static native String JNIfmodstudioeventdescriptiongetparameterlabelbyindex(double arg0,double arg1,double arg2);
	public static native double JNIfmodstudioeventdescriptiongetuserpropertymultiplatform(double arg0,String arg1,ByteBuffer arg2);
	public static native double JNIfmodstudioeventdescriptiongetuserpropertybyindexmultiplatform(double arg0,double arg1,ByteBuffer arg2);
	public static native double JNIfmodstudioeventdescriptiongetuserpropertycount(double arg0);
	public static native String JNIfmodstudioeventdescriptiongetid(double arg0);
	public static native double JNIfmodstudioeventdescriptiongetlength(double arg0);
	public static native String JNIfmodstudioeventdescriptiongetpath(double arg0);
	public static native double JNIfmodstudioeventdescriptionsetcallback(double arg0,double arg1);
	public static native double JNIfmodstudioeventdescriptionsetuserdata(double arg0,double arg1);
	public static native double JNIfmodstudioeventdescriptiongetuserdata(double arg0);
	public static native double JNIfmodstudioeventdescriptionisvalid(double arg0);
	public static native double JNIfmodstudioeventinstancestart(double arg0);
	public static native double JNIfmodstudioeventinstancestop(double arg0,double arg1);
	public static native double JNIfmodstudioeventinstancegetplaybackstate(double arg0);
	public static native double JNIfmodstudioeventinstancesetpaused(double arg0,double arg1);
	public static native double JNIfmodstudioeventinstancegetpaused(double arg0);
	public static native double JNIfmodstudioeventinstancekeyoff(double arg0);
	public static native double JNIfmodstudioeventinstancesetpitch(double arg0,double arg1);
	public static native double JNIfmodstudioeventinstancegetpitch(double arg0);
	public static native double JNIfmodstudioeventinstancesetproperty(double arg0,double arg1,double arg2);
	public static native double JNIfmodstudioeventinstancegetproperty(double arg0,double arg1);
	public static native double JNIfmodstudioeventinstancesettimelineposition(double arg0,double arg1);
	public static native double JNIfmodstudioeventinstancegettimelineposition(double arg0);
	public static native double JNIfmodstudioeventinstancesetvolume(double arg0,double arg1);
	public static native double JNIfmodstudioeventinstancegetvolumemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudioeventinstanceisvirtual(double arg0);
	public static native double JNIfmodstudioeventinstanceset3dattributesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudioeventinstanceget3dattributesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudioeventinstancesetlistenermask(double arg0,double arg1);
	public static native double JNIfmodstudioeventinstancegetlistenermask(double arg0);
	public static native double JNIfmodstudioeventinstancegetminmaxdistancemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudioeventinstancesetparameterbynamemultiplatform(double arg0,String arg1,double arg2,double arg3);
	public static native double JNIfmodstudioeventinstancesetparameterbynamewithlabel(double arg0,String arg1,String arg2,double arg3);
	public static native double JNIfmodstudioeventinstancegetparameterbynamemultiplatform(double arg0,String arg1,ByteBuffer arg2);
	public static native double JNIfmodstudioeventinstancesetparameterbyidmultiplatform(double arg0,ByteBuffer arg1,double arg2,double arg3);
	public static native double JNIfmodstudioeventinstancesetparameterbyidwithlabelmultiplatform(double arg0,ByteBuffer arg1,String arg2,double arg3);
	public static native double JNIfmodstudioeventinstancegetparameterbyidmultiplatform(double arg0,ByteBuffer arg1,ByteBuffer arg2);
	public static native double JNIfmodstudioeventinstancegetchannelgroup(double arg0);
	public static native double JNIfmodstudioeventinstancesetreverblevel(double arg0,double arg1,double arg2);
	public static native double JNIfmodstudioeventinstancegetreverblevel(double arg0,double arg1);
	public static native double JNIfmodstudioeventinstancegetcpuusagemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudioeventinstancegetmemoryusagemultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudioeventinstancesetcallback(double arg0,double arg1);
	public static native double JNIfmodstudioeventinstancesetuserdata(double arg0,double arg1);
	public static native double JNIfmodstudioeventinstancegetuserdata(double arg0);
	public static native double JNIfmodstudioeventinstancegetdescription(double arg0);
	public static native double JNIfmodstudioeventinstancerelease(double arg0);
	public static native double JNIfmodstudioeventinstanceisvalid(double arg0);
	public static native double JNIfmodstudiosystemcreate();
	public static native double JNIfmodstudiosysteminit(double arg0,double arg1,double arg2);
	public static native double JNIfmodstudiosystemrelease();
	public static native double JNIfmodstudiosystemupdatemultiplatform();
	public static native double JNIfmodstudiosystemflushcommands();
	public static native double JNIfmodstudiosystemflushsampleloading();
	public static native double JNIfmodstudiosystemloadbankcustom(double arg0);
	public static native double JNIfmodstudiosystemloadbankfile(String arg0,double arg1);
	public static native double JNIfmodstudiosystemloadbankmemorymultiplatform(ByteBuffer arg0,double arg1,double arg2,double arg3);
	public static native double JNIfmodstudiosystemunloadall();
	public static native double JNIfmodstudiosystemgetbank(String arg0);
	public static native double JNIfmodstudiosystemgetbankbyid(String arg0);
	public static native double JNIfmodstudiosystemgetbankcount();
	public static native double JNIfmodstudiosystemgetbanklistmultiplatform(ByteBuffer arg0);
	public static native double JNIfmodstudiosystemsetlistenerattributesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiosystemgetlistenerattributesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiosystemsetlistenerweight(double arg0,double arg1);
	public static native double JNIfmodstudiosystemgetlistenerweight(double arg0);
	public static native double JNIfmodstudiosystemsetnumlisteners(double arg0);
	public static native double JNIfmodstudiosystemgetnumlisteners();
	public static native double JNIfmodstudiosystemgetbus(String arg0);
	public static native double JNIfmodstudiosystemgetbusbyid(String arg0);
	public static native double JNIfmodstudiosystemgetevent(String arg0);
	public static native double JNIfmodstudiosystemgeteventbyid(String arg0);
	public static native double JNIfmodstudiosystemgetparameterbyidmultiplatform(ByteBuffer arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiosystemsetparameterbyidmultiplatform(ByteBuffer arg0,double arg1,double arg2);
	public static native double JNIfmodstudiosystemsetparameterbyidwithlabelmultiplatform(ByteBuffer arg0,String arg1,double arg2);
	public static native double JNIfmodstudiosystemgetparameterbynamemultiplatform(String arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiosystemsetparameterbynamemultiplatform(String arg0,double arg1,double arg2);
	public static native double JNIfmodstudiosystemsetparameterbynamewithlabelmultiplatform(String arg0,String arg1,double arg2);
	public static native double JNIfmodstudiosystemgetparameterdescriptionbynamemultiplatform(String arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiosystemgetparameterdescriptionbyidmultiplatform(ByteBuffer arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiosystemgetparameterdescriptioncount();
	public static native double JNIfmodstudiosystemgetparameterdescriptionlistmultiplatform(ByteBuffer arg0);
	public static native String JNIfmodstudiosystemgetparameterlabelbyname(String arg0,double arg1);
	public static native String JNIfmodstudiosystemgetparameterlabelbyidmultiplatform(ByteBuffer arg0,double arg1);
	public static native double JNIfmodstudiosystemgetvca(String arg0);
	public static native double JNIfmodstudiosystemgetvcabyid(String arg0);
	public static native double JNIfmodstudiosystemsetadvancedsettingsmultiplatform(ByteBuffer arg0);
	public static native double JNIfmodstudiosystemgetadvancedsettingsmultiplatform(ByteBuffer arg0);
	public static native double JNIfmodstudiosystemstartcommandcapture(String arg0,double arg1);
	public static native double JNIfmodstudiosystemstopcommandcapture();
	public static native double JNIfmodstudiosystemloadcommandreplay(String arg0,double arg1);
	public static native double JNIfmodstudiosystemgetbufferusagemultiplatform(ByteBuffer arg0);
	public static native double JNIfmodstudiosystemresetbufferusage();
	public static native double JNIfmodstudiosystemgetcpuusagemultiplatform(ByteBuffer arg0);
	public static native double JNIfmodstudiosystemgetmemoryusagemultiplatform(ByteBuffer arg0);
	public static native double JNIfmodstudiosystemsetcallback(double arg0);
	public static native double JNIfmodstudiosystemsetuserdata(double arg0);
	public static native double JNIfmodstudiosystemgetuserdata();
	public static native double JNIfmodstudiosystemgetsoundinfomultiplatform(String arg0,ByteBuffer arg1);
	public static native double JNIfmodstudiosystemgetcoresystem();
	public static native String JNIfmodstudiosystemlookupid(String arg0);
	public static native String JNIfmodstudiosystemlookuppath(String arg0);
	public static native double JNIfmodstudiosystemisvalid();
	public static native double JNIfmodstudiovcasetvolume(double arg0,double arg1);
	public static native double JNIfmodstudiovcagetvolume(double arg0);
	public static native String JNIfmodstudiovcagetid(double arg0);
	public static native String JNIfmodstudiovcagetpath(double arg0);
	public static native double JNIfmodstudiovcaisvalid(double arg0);
	public static native double JNIfmodsystemcreate();
	public static native double JNIfmodsystemselect(double arg0);
	public static native double JNIfmodsystemcount();
	public static native double JNIfmodsysteminit(double arg0,double arg1);
	public static native double JNIfmodsystemrelease(double arg0);
	public static native double JNIfmodsystemclose(double arg0);
	public static native double JNIfmodsystemupdatemultiplatform();
	public static native double JNIfmodsystemmixersuspend();
	public static native double JNIfmodsystemmixerresume();
	public static native double JNIfmodsystemsetoutput(double arg0);
	public static native double JNIfmodsystemgetoutput();
	public static native double JNIfmodsystemgetnumdrivers();
	public static native double JNIfmodsystemgetdriverinfomultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsystemsetdriver(double arg0);
	public static native double JNIfmodsystemgetdriver();
	public static native double JNIfmodsystemsetsoftwarechannels(double arg0);
	public static native double JNIfmodsystemgetsoftwarechannels();
	public static native double JNIfmodsystemsetsoftwareformat(double arg0,double arg1,double arg2);
	public static native double JNIfmodsystemgetsoftwareformatmultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemsetdspbuffersize(double arg0,double arg1);
	public static native double JNIfmodsystemgetdspbuffersizemultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemsetstreambuffersize(double arg0,double arg1);
	public static native double JNIfmodsystemgetstreambuffersizemultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemsetadvancedsettingsmultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemgetadvancedsettingsmultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemsetspeakerposition(double arg0,double arg1,double arg2,double arg3);
	public static native double JNIfmodsystemgetspeakerpositionmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsystemset3dsettings(double arg0,double arg1,double arg2);
	public static native double JNIfmodsystemget3dsettingsmultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemset3dnumlisteners(double arg0);
	public static native double JNIfmodsystemget3dnumlisteners();
	public static native double JNIfmodsystemset3drolloffcallback();
	public static native double JNIfmodsystemsetnetworkproxy(String arg0);
	public static native String JNIfmodsystemgetnetworkproxy();
	public static native double JNIfmodsystemsetnetworktimeout(double arg0);
	public static native double JNIfmodsystemgetnetworktimeout();
	public static native double JNIfmodsystemgetversion();
	public static native double JNIfmodsystemgetchannelsplayingmultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemgetcpuusagemultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemgetfileusagemultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemgetdefaultmixmatrixmultiplatform(double arg0,double arg1,double arg2,ByteBuffer arg3);
	public static native double JNIfmodsystemgetspeakermodechannels(double arg0);
	public static native double JNIfmodsystemcreatesoundmultiplatform(String arg0,double arg1,ByteBuffer arg2);
	public static native double JNIfmodsystemcreatestreammultiplatform(String arg0,double arg1,ByteBuffer arg2);
	public static native double JNIfmodsystemcreatedsp();
	public static native double JNIfmodsystemcreatedspbytype(double arg0);
	public static native double JNIfmodsystemcreatechannelgroup(String arg0);
	public static native double JNIfmodsystemcreatesoundgroup(String arg0);
	public static native double JNIfmodsystemcreatereverb3d();
	public static native double JNIfmodsystemplaysoundmultiplatform(double arg0,double arg1,double arg2);
	public static native double JNIfmodsystemplaydspmultiplatform(double arg0,double arg1,double arg2);
	public static native double JNIfmodsystemgetchannel(double arg0);
	public static native double JNIfmodsystemgetmasterchannelgroup();
	public static native double JNIfmodsystemgetmastersoundgroup();
	public static native double JNIfmodsystemset3dlistenerattributesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsystemget3dlistenerattributesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsystemsetreverbpropertiesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsystemgetreverbpropertiesmultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsystemattachchannelgrouptoportmultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemdetachchannelgroupfromport(double arg0);
	public static native double JNIfmodsystemgetrecordnumdriversmultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemgetrecorddriverinfomultiplatform(double arg0,ByteBuffer arg1);
	public static native double JNIfmodsystemgetrecordposition(double arg0);
	public static native double JNIfmodsystemrecordstart(double arg0,double arg1,double arg2);
	public static native double JNIfmodsystemrecordstop(double arg0);
	public static native double JNIfmodsystemisrecording(double arg0);
	public static native double JNIfmodsystemcreategeometry(double arg0,double arg1);
	public static native double JNIfmodsystemsetgeometrysettings(double arg0);
	public static native double JNIfmodsystemgetgeometrysettings();
	public static native double JNIfmodsystemloadgeometrymultiplatform(ByteBuffer arg0,double arg1);
	public static native double JNIfmodsystemgetgeometryocclusionmultiplatform(ByteBuffer arg0);
	public static native double JNIfmodsystemlockdsp();
	public static native double JNIfmodsystemunlockdsp();
	public static native double JNIfmodsystemsetcallback(double arg0);
	public static native double JNIfmodsystemsetuserdata(double arg0,double arg1);
	public static native double JNIfmodsystemgetuserdata(double arg0);
	public static native double JNIfmodfetchcallbacks(ByteBuffer arg0,double arg1);
	public static native double JNIfmodlastresult();


    static { System.loadLibrary("YYFMOD"); }
}