name: Extension Bug Report
description: File a bug report for issues that happen with any of our Official Extensions.
labels: ["extension-bug"]
body:
  - type: markdown
    attributes:
      value: |
        For any GameMaker Account or licencing issues (including "I can't see all my platforms in Target Manager") please submit a [Helpdesk Ticket](https://contact.gamemaker.io/contact-us#account) instead of using this form.
        
        Please also ensure you have searched for any existing reports of this issue before you begin - if one exists, please leave a thumbs-up on that one, rather than knowingly filing a duplicate report, as duplicates just slow things down.
       
        Note that most fields are required to be filled-in before you can submit this report, as it is all essential information which we will require in order to confirm and fix your issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a concise yet detailed description of the issue and do include any relevant screenshots at suitable locations in the body of your text. Please do not copy/paste lots of code in this field - attach a sample project instead, as requested below. (Also, do not add a web link as your entire bug report and assume we will read the external thread to work it out ourselves, as we will most likely simply close the report!)
    validations:
      required: true
      
  - type: input
    id: expected
    attributes:
      label: Expected Change
      description: If it is not obvious from your Description text, what difference would you expect to see once this is fixed?
    validations:
      required: false
      
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Add the detailed, ordered steps for someone else to reproduce the issue into the gaps below (add as many steps into the middle as you require)
      value: |
        1. Start GameMaker
        2. 
        3. 
        4. See the issue
    validations:
      required: true
      
  - type: dropdown
    id: repro-rate
    attributes:
      label: How reliably can you recreate this issue using your steps above?
      options:
        - Always
        - Most Times
        - Only Sometimes
        - Rarely
        - Only Ever Happened Once 
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: Which version of GameMaker are you reporting this issue for?
      description: Please put the exact version number in your Description (If your version is older and therefore not in this list, please update and confirm your issue is not already fixed before you send any report!)
      multiple: true
      options:
        - Monthly
        - LTS
        - Beta
        - Other Release
    validations:
      required: true
      
  - type: dropdown
    id: platforms
    attributes:
      label: Which platform(s) are you seeing the problem on?
      multiple: true
      options: 
        - Windows
        - macOS
        - Ubuntu
        - Android
        - iOS
        - tvOS
        - HTML5
        - GX.games
        - PlayStation 4
        - PlayStation 5
        - Switch
        - Xbox (GDK)
    validations:
      required: false
      
  - type: checkboxes
    id: compile-log
    attributes:
      label: Compiler Log File
      description: Please copy/paste your entire _Output Window_ contents from GameMaker into a new .txt file and ensure you have dropped that .txt file onto this bug report form, then tick the checkbox to confirm you have done so. This file is essential for all compilation and in-game bug reports.
      options:
        - label: I have attached my compiler log in a text file
          required: true
          
  - type: checkboxes
    id: sample
    attributes:
      label: Sample .yyz File
      description: Please _Export_ as small a sample project as you can make to recreate the issue and drop the .yyz file GameMaker made for you onto this bug report form, then tick the checkbox to confirm you have done so. This file is often extremely important for in-game bug reports and we will ask for a sample if the issue does not easily reproduce for us.
      options:
        - label: I have attached a small sample project
          required: false
          
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
