// ##### extgen :: Auto-generated file do not edit!! #####

#pragma once
#include "core/GMExtUtils.h"

// Internal function used for fetching dispatched function calls to GML
GMEXPORT double __EXT_NATIVE__GMFMOD_invocation_handler(char* __ret_buffer, double __ret_buffer_length);

GMEXPORT double __EXT_NATIVE__fmod_last_result(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_debug_initialize(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_path_bundle(char* filename);
GMEXPORT char* __EXT_NATIVE__fmod_path_user(char* filename);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_frequency(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_frequency(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_priority(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_priority(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_channel_group(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_channel_group(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_loop_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_loop_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_loop_points(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_is_virtual(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_current_sound(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_create(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_init(double max_channels, double flags);
GMEXPORT double __EXT_NATIVE__fmod_system_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_close(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_update();
GMEXPORT double __EXT_NATIVE__fmod_system_get_channel(double index, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_get_master_channel_group(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_set_output(double output);
GMEXPORT double __EXT_NATIVE__fmod_system_get_output();
GMEXPORT double __EXT_NATIVE__fmod_system_get_num_drivers();
GMEXPORT double __EXT_NATIVE__fmod_system_set_driver(double driver);
GMEXPORT double __EXT_NATIVE__fmod_system_get_driver();
GMEXPORT double __EXT_NATIVE__fmod_system_set_software_channels(double software_channels);
GMEXPORT double __EXT_NATIVE__fmod_system_get_software_channels();
GMEXPORT double __EXT_NATIVE__fmod_system_create_sound(char* name_or_data, double mode, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_create_stream(char* name_or_data, double mode, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_play_sound(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_length(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_defaults(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_mode(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_mode(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_loop_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_loop_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_loop_points(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_3d_min_max_distance(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_3d_cone_settings(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_num_channels(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_channel(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_add_group(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_num_groups(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_group(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_parent_group(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_channel_group_get_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_set_max_audible(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_max_audible(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_set_max_audible_behavior(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_max_audible_behavior(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_set_mute_fade_speed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_mute_fade_speed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_num_sounds(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_sound(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_num_playing(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_stop(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_sound_group_get_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_reverb_3d_set_active(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_reverb_3d_get_active(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_reverb_3d_set_properties(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_reverb_3d_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_is_playing(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_stop(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_paused(double channel_control_ref, double paused);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_paused(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_mode(double channel_control_ref, double mode);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_mode(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_pitch(double channel_control_ref, double pitch);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_pitch(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_audibility(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_volume(double channel_control_ref, double volume);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_volume(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_volume_ramp(double channel_control_ref, double ramp);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_volume_ramp(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_mute(double channel_control_ref, double mute);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_mute(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_doppler_level(double channel_control_ref, double level);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_3d_doppler_level(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_level(double channel_control_ref, double level);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_3d_level(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_min_max_distance(double channel_control_ref, double min_dist, double max_dist);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_cone_settings(double channel_control_ref, double inside_cone_angle, double outside_cone_angle, double outside_volume);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_occlusion(double channel_control_ref, double direct_occlusion, double reverb_occlusion);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_spread(double channel_control_ref, double angle);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_3d_spread(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_distance_filter(double channel_control_ref, double custom, double custom_level, double center_freq);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_pan(double channel_control_ref, double pan);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_mix_levels_output(double channel_control_ref, double front_left, double front_right, double center, double lfe, double surround_left, double surround_right, double back_left, double back_right);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_reverb_properties(double channel_control_ref, double reverb_instance, double wet);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_reverb_properties(double channel_control_ref, double reverb_instance);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_low_pass_gain(double channel_control_ref, double gain);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_low_pass_gain(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_add_dsp(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_remove_dsp(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_num_dsps(double channel_control_ref);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_dsp(double channel_control_ref, double index, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_dsp_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_dsp_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_system_object(double channel_control_ref, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_add_input(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_num_inputs(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_num_outputs(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_disconnect_all(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_num_parameters(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_parameter_float(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_parameter_float(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_parameter_int(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_parameter_int(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_parameter_bool(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_parameter_bool(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_set_polygon_attributes(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_get_polygon_num_vertices(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_set_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_set_rotation(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_set_scale(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_save(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_create(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_init(double max_channels, double studio_flags, double core_flags);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_release();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_update();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_flush_commands();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_flush_sample_loading();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_load_bank_file(char* filename, double flags, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_load_bank_memory(char* data, double flags, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_unload_all();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bank_count();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bank_at(double index, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bank(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_event(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_create_event_instance(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bus(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_master_bus(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_vca(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_listener_attributes(double listener_index, double x, double y, double z);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_listener_weight(double listener_index, double weight);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_parameter_by_name(char* name, double value);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_parameter_by_name(char* name);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_core_system(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_unload(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_loading_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_sample_loading_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_bank_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_parent_studio_system(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_event_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_event_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_bus_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_bus_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_vca_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_vca_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_string_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_event_description_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_create_instance(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_instance_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_instance_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_is_snapshot(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_is_one_shot(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_has_sustain_point(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_length(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_parameter_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_release_all_instances(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_start(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_stop(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_playback_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_timeline_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_timeline_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_pitch(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_pitch(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_parameter_by_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_parameter_by_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_parameter_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_3d_attributes(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_description(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_bus_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_set_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_stop_all_events(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_master_bus(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_vca_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_vca_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_vca_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_playback_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_current_command(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_frame_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_create_instance_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_load_bank_callback(char* __arg_buffer, double __arg_buffer_length);

