// ##### extgen :: Auto-generated file do not edit!! #####

#pragma once
#include "core/GMExtUtils.h"

// Internal function used for fetching dispatched function calls to GML
GMEXPORT double __EXT_NATIVE__GMFMOD_invocation_handler(char* __ret_buffer, double __ret_buffer_length);

// Internal function used for queueing buffers to native code
GMEXPORT double __EXT_NATIVE__GMFMOD_queue_buffer(char* __arg_buffer, double __arg_buffer_length);

GMEXPORT double __EXT_NATIVE__fmod_last_result(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_debug_initialize(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_path_bundle(char* filename);
GMEXPORT char* __EXT_NATIVE__fmod_path_user(char* filename);
GMEXPORT char* __EXT_NATIVE__fmod_error_string(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_frequency(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_frequency(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_priority(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_priority(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_channel_group(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_channel_group(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_loop_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_loop_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_set_loop_points(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_is_virtual(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_current_sound(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_create(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_init(double max_channels, double flags);
GMEXPORT double __EXT_NATIVE__fmod_system_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_close(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_update();
GMEXPORT double __EXT_NATIVE__fmod_system_get_channels_playing();
GMEXPORT double __EXT_NATIVE__fmod_system_get_channel(double index, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_get_master_channel_group(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_set_output(double output);
GMEXPORT double __EXT_NATIVE__fmod_system_get_output();
GMEXPORT double __EXT_NATIVE__fmod_system_get_num_drivers();
GMEXPORT double __EXT_NATIVE__fmod_system_set_driver(double driver);
GMEXPORT double __EXT_NATIVE__fmod_system_get_driver();
GMEXPORT double __EXT_NATIVE__fmod_system_set_software_channels(double software_channels);
GMEXPORT double __EXT_NATIVE__fmod_system_get_software_channels();
GMEXPORT double __EXT_NATIVE__fmod_system_set_3d_settings(double doppler_scale, double distance_factor, double rolloff_scale);
GMEXPORT double __EXT_NATIVE__fmod_system_get_3d_settings(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_set_3d_listener_attributes(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_get_3d_listener_attributes(double listener_index, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_get_record_num_drivers();
GMEXPORT double __EXT_NATIVE__fmod_system_get_record_driver_info(double record_driver_index, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_get_record_position(double device_index);
GMEXPORT double __EXT_NATIVE__fmod_system_record_start(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_record_stop(double device_index);
GMEXPORT double __EXT_NATIVE__fmod_system_is_recording(double device_index);
GMEXPORT double __EXT_NATIVE__fmod_system_create_dsp(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_create_dsp_by_type(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_get_dsp_buffer_size(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_set_dsp_buffer_size(double buff_size, double num_buffers);
GMEXPORT double __EXT_NATIVE__fmod_system_get_software_format(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_set_software_format(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_set_stream_buffer_size(double file_buffer_size, double file_buffer_size_type);
GMEXPORT double __EXT_NATIVE__fmod_system_get_driver_info(double driver_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_create_channel_group(char* name, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_play_dsp(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_select(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_create_sound(char* name_or_data, double mode, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_create_stream(char* name_or_data, double mode, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_system_play_sound(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_length(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_defaults(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_mode(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_mode(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_format(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_sound_get_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_defaults(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_loop_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_loop_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_loop_points(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_loop_points(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_3d_min_max_distance(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_3d_min_max_distance(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_3d_cone_settings(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_3d_cone_settings(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_3d_custom_rolloff(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_3d_custom_rolloff(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_num_sync_points(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_sync_point(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_add_sync_point(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_delete_sync_point(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_music_num_channels(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_music_channel_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_music_channel_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_music_speed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_music_speed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_set_sound_group(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_sound_group(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_open_state(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_tag(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_num_sub_sounds(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_get_sub_sound(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_read_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_num_channels(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_channel(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_add_group(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_num_groups(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_group(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_parent_group(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_channel_group_get_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_group_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_set_max_audible(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_max_audible(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_set_max_audible_behavior(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_max_audible_behavior(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_set_mute_fade_speed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_mute_fade_speed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_num_sounds(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_sound(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_num_playing(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_stop(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_sound_group_get_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_sound_group_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_reverb_3d_set_active(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_reverb_3d_get_active(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_reverb_3d_set_properties(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_reverb_3d_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_is_playing(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_stop(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_mode(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_mode(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_pitch(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_pitch(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_audibility(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_volume_ramp(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_volume_ramp(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_mute(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_mute(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_doppler_level(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_3d_doppler_level(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_level(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_3d_level(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_min_max_distance(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_cone_settings(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_occlusion(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_attributes(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_3d_attributes(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_spread(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_3d_spread(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_3d_distance_filter(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_pan(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_mix_levels_output(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_reverb_properties(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_reverb_properties(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_low_pass_gain(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_low_pass_gain(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_add_dsp(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_remove_dsp(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_num_dsps(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_dsp(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_dsp_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_dsp_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_delay(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_delay(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_get_dsp_clock(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_channel_control_set_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_add_input(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_num_inputs(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_num_outputs(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_disconnect_all(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_num_parameters(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_parameter_float(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_parameter_float(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_parameter_int(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_parameter_int(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_parameter_bool(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_parameter_bool(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_input(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_output(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_disconnect_from(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_data_parameter_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_parameter_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_parameter_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_parameter_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_channel_format(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_channel_format(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_output_channel_format(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_metering_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_metering_enabled(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_metering_enabled(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_active(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_active(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_bypass(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_bypass(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_wet_dry_mix(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_wet_dry_mix(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_idle(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_reset(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_type(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_cpu_usage(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_get_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_set_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_connection_set_mix(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_connection_get_mix(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_connection_set_mix_matrix(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_connection_get_mix_matrix(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_connection_get_input(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_connection_get_output(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_connection_get_type(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_connection_set_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_dsp_connection_get_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_set_polygon_attributes(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_get_polygon_num_vertices(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_set_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_set_rotation(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_set_scale(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_save(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_geometry_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_create(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_init(double max_channels, double studio_flags, double core_flags);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_release();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_update();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_flush_commands();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_flush_sample_loading();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_load_bank_file(char* filename, double flags, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_load_bank_memory(char* data, double flags, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_unload_all();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bank_count();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bank_at(double index, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bank(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_event(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_create_event_instance(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bus(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_master_bus(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_vca(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_listener_attributes(double listener_index, double x, double y, double z);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_listener_weight(double listener_index, double weight);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_parameter_by_name(char* name, double value);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_parameter_by_name(char* name);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_core_system(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_num_listeners(double count);
GMEXPORT char* __EXT_NATIVE__fmod_studio_system_lookup_id(char* path);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_event_by_id(char* id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_start_command_capture(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_stop_command_capture();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_load_command_replay(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_unload(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_loading_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_sample_loading_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_bank_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_parent_studio_system(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_event_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_event_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_bus_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_bus_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_vca_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_vca_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_string_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_event_description_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_create_instance(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_instance_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_instance_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_is_snapshot(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_is_one_shot(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_has_sustain_point(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_length(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_parameter_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_release_all_instances(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_parameter_description_by_name(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_load_sample_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_start(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_stop(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_playback_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_timeline_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_timeline_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_pitch(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_pitch(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_parameter_by_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_parameter_by_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_parameter_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_parameter_by_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_parameter_by_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_3d_attributes(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_description(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_bus_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_set_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_stop_all_events(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_master_bus(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_vca_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_vca_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_vca_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_playback_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_current_command(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_command_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_length(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_frame_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_create_instance_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_load_bank_callback(char* __arg_buffer, double __arg_buffer_length);

