// ##### extgen :: Auto-generated file do not edit!! #####

#pragma once
#include "core/GMExtUtils.h"

// Internal function used for fetching dispatched function calls to GML
GMEXPORT double __EXT_NATIVE__GMFMODStudio_invocation_handler(char* __ret_buffer, double __ret_buffer_length);

GMEXPORT double __EXT_NATIVE__fmod_studio_system_create(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_init(double max_channels, double studio_flags, double core_flags);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_release();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_update();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_flush_commands();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_flush_sample_loading();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_load_bank_file(char* filename, double flags, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_load_bank_memory(char* data, double flags, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_unload_all();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bank_count();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bank_at(double index, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bank(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bank_by_id(char* str_guid, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_event(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_create_event_instance(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bus(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_master_bus(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_bus_by_id(char* str_guid, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_vca(char* path, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_vca_by_id(char* str_guid, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_listener_attributes(double listener_index, double x, double y, double z);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_listener_weight(double listener_index, double weight);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_num_listeners();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_listener_attributes(double listener_index, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_listener_weight(double listener_index);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_parameter_by_name(char* name, double value);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_parameter_by_name(char* name);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_core_system(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_num_listeners(double count);
GMEXPORT char* __EXT_NATIVE__fmod_studio_system_lookup_id(char* path);
GMEXPORT char* __EXT_NATIVE__fmod_studio_system_lookup_path(char* str_guid);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_event_by_id(char* id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_is_valid();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_start_command_capture(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_stop_command_capture();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_load_command_replay(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_sound_info(char* key, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_parameter_by_id(double id_data1, double id_data2, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_parameter_by_id(double id_data1, double id_data2, double value, double ignore_seek_speed);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_parameter_description_by_id(double id_data1, double id_data2, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_parameter_description_by_name(char* name, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_parameter_description_count();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_parameter_description_at(double index, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_system_get_parameter_label_by_id(double id_data1, double id_data2, double label_index);
GMEXPORT char* __EXT_NATIVE__fmod_studio_system_get_parameter_label_by_name(char* name, double label_index);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_parameter_by_id_with_label(double id_data1, double id_data2, char* label, double ignore_seek_speed);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_parameter_by_name_with_label(char* name, char* label, double ignore_seek_speed);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_cpu_usage(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_buffer_usage(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_reset_buffer_usage();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_memory_usage(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_advanced_settings(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_advanced_settings(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_callback(double callback_mask);
GMEXPORT double __EXT_NATIVE__fmod_studio_system_get_user_data();
GMEXPORT double __EXT_NATIVE__fmod_studio_system_set_user_data(double user_data);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_unload(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_loading_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_sample_loading_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_bank_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_parent_studio_system(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_event_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_event_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_bus_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_bus_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_vca_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_vca_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_string_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_bank_get_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_string_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_load_sample_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_unload_sample_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_get_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bank_set_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_event_description_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_create_instance(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_instance_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_instance_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_is_snapshot(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_is_one_shot(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_has_sustain_point(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_length(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_parameter_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_release_all_instances(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_parameter_description_by_name(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_load_sample_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_is_3d(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_is_stream(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_is_doppler_enabled(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_event_description_get_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_min_max_distance(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_sound_size(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_sample_loading_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_unload_sample_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_set_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_set_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_user_property(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_user_property_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_user_property_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_parameter_description_by_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_description_get_parameter_description_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_event_description_get_parameter_label_by_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_event_description_get_parameter_label_at(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_event_description_get_parameter_label_by_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_start(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_stop(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_playback_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_timeline_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_timeline_position(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_keyoff(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_pitch(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_pitch(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_parameter_by_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_parameter_by_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_parameter_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_parameter_by_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_parameter_by_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_parameter_by_id_with_label(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_parameter_by_name_with_label(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_3d_attributes(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_3d_attributes(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_min_max_distance(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_listener_mask(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_listener_mask(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_reverb_level(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_reverb_level(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_property(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_property(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_set_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_is_virtual(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_channel_group(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_cpu_usage(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_memory_usage(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_get_description(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_event_instance_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_bus_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_set_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_stop_all_events(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_master_bus(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_bus_get_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_channel_group(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_lock_channel_group(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_unlock_channel_group(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_cpu_usage(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_memory_usage(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_mute(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_set_mute(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_get_port_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_bus_set_port_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_vca_get_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_vca_get_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_vca_set_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_playback_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_current_command(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_command_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_length(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_system_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_command_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__fmod_studio_command_replay_get_command_string(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_command_at_time(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_seek_to_command(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_seek_to_time(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_bank_path(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_paused(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_start(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_stop(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_get_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_user_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_frame_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_create_instance_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__fmod_studio_command_replay_set_load_bank_callback(char* __arg_buffer, double __arg_buffer_length);

