package com.gamemaker.ExtensionCore.ExtBridge;
import java.lang.String;
import java.nio.ByteBuffer;
import ${YYAndroidPackageName}.GMExtUtils;

public final class GMFMODStudioBridge {
    static {
        // this is the extension lib name
        System.loadLibrary("GMFMODStudio");
        nativeRegister();
    }
    // this registers the native functions on the C++ layer
    private static native void nativeRegister();

    public static String __EXT_JAVA__GetExtensionOption(String extName, String optName)
    {
        return GMExtUtils.GetExtensionOption(extName, optName);
    }

    public static native double __EXT_JNI__GMFMODStudio_invocation_handler(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_create(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_init(double max_channels, double studio_flags, double core_flags);
    public static native double __EXT_JNI__fmod_studio_system_release();
    public static native double __EXT_JNI__fmod_studio_system_update();
    public static native double __EXT_JNI__fmod_studio_system_flush_commands();
    public static native double __EXT_JNI__fmod_studio_system_flush_sample_loading();
    public static native double __EXT_JNI__fmod_studio_system_load_bank_file(String filename, double flags, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_load_bank_memory(String data, double flags, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_unload_all();
    public static native double __EXT_JNI__fmod_studio_system_get_bank_count();
    public static native double __EXT_JNI__fmod_studio_system_get_bank_at(double index, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_bank(String path, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_bank_by_id(String str_guid, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_event(String path, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_create_event_instance(String path, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_bus(String path, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_master_bus(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_bus_by_id(String str_guid, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_vca(String path, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_vca_by_id(String str_guid, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_set_listener_attributes(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_set_listener_weight(double listener_index, double weight);
    public static native double __EXT_JNI__fmod_studio_system_get_num_listeners();
    public static native double __EXT_JNI__fmod_studio_system_get_listener_attributes(double listener_index, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_listener_weight(double listener_index);
    public static native double __EXT_JNI__fmod_studio_system_set_parameter_by_name(String name, double value);
    public static native double __EXT_JNI__fmod_studio_system_get_parameter_by_name(String name);
    public static native double __EXT_JNI__fmod_studio_system_get_core_system(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_core_system_ptr(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_last_result(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_shutdown();
    public static native double __EXT_JNI__fmod_studio_system_set_num_listeners(double count);
    public static native String __EXT_JNI__fmod_studio_system_lookup_id(String path);
    public static native String __EXT_JNI__fmod_studio_system_lookup_path(String str_guid);
    public static native double __EXT_JNI__fmod_studio_system_get_event_by_id(String id, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_is_valid();
    public static native double __EXT_JNI__fmod_studio_system_start_command_capture(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_stop_command_capture();
    public static native double __EXT_JNI__fmod_studio_system_load_command_replay(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_sound_info(String key, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_parameter_by_id(double id_data1, double id_data2, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_set_parameter_by_id(double id_data1, double id_data2, double value, double ignore_seek_speed);
    public static native double __EXT_JNI__fmod_studio_system_get_parameter_description_by_id(double id_data1, double id_data2, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_parameter_description_by_name(String name, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_parameter_description_count();
    public static native double __EXT_JNI__fmod_studio_system_get_parameter_description_at(double index, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native String __EXT_JNI__fmod_studio_system_get_parameter_label_by_id(double id_data1, double id_data2, double label_index);
    public static native String __EXT_JNI__fmod_studio_system_get_parameter_label_by_name(String name, double label_index);
    public static native double __EXT_JNI__fmod_studio_system_set_parameter_by_id_with_label(double id_data1, double id_data2, String label, double ignore_seek_speed);
    public static native double __EXT_JNI__fmod_studio_system_set_parameter_by_name_with_label(String name, String label, double ignore_seek_speed);
    public static native double __EXT_JNI__fmod_studio_system_get_cpu_usage(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_buffer_usage(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_reset_buffer_usage();
    public static native double __EXT_JNI__fmod_studio_system_get_memory_usage(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_get_advanced_settings(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_set_advanced_settings(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_system_set_callback(double callback_mask);
    public static native double __EXT_JNI__fmod_studio_system_get_user_data();
    public static native double __EXT_JNI__fmod_studio_system_set_user_data(double user_data);
    public static native double __EXT_JNI__fmod_studio_bank_unload(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_loading_state(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_sample_loading_state(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_studio_bank_get_path(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_parent_studio_system(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_event_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_event_at(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_bus_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_bus_at(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_vca_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_vca_at(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_string_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_studio_bank_get_id(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_is_valid(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_string_info(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_load_sample_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_unload_sample_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_get_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bank_set_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_studio_event_description_get_path(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_create_instance(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_instance_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_instance_at(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_is_snapshot(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_is_one_shot(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_has_sustain_point(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_length(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_parameter_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_release_all_instances(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_parameter_description_by_name(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_load_sample_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_is_valid(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_is_3d(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_is_stream(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_is_doppler_enabled(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_studio_event_description_get_id(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_min_max_distance(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_sound_size(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_sample_loading_state(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_unload_sample_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_set_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_set_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_user_property(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_user_property_at(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_user_property_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_parameter_description_by_id(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_description_get_parameter_description_at(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native String __EXT_JNI__fmod_studio_event_description_get_parameter_label_by_id(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_studio_event_description_get_parameter_label_at(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_studio_event_description_get_parameter_label_by_name(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_start(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_stop(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_playback_state(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_timeline_position(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_timeline_position(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_keyoff(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_pitch(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_pitch(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_parameter_by_name(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_parameter_by_name(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_parameter_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_parameter_by_id(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_parameter_by_id(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_parameter_by_id_with_label(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_parameter_by_name_with_label(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_3d_attributes(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_3d_attributes(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_min_max_distance(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_listener_mask(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_listener_mask(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_reverb_level(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_reverb_level(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_property(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_property(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_set_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_is_valid(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_is_virtual(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_channel_group(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_cpu_usage(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_memory_usage(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_get_description(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_event_instance_release(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_studio_bus_get_path(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_get_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_set_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_get_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_set_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_stop_all_events(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_get_master_bus(ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native String __EXT_JNI__fmod_studio_bus_get_id(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_is_valid(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_get_channel_group(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_lock_channel_group(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_unlock_channel_group(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_get_cpu_usage(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_get_memory_usage(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_get_mute(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_set_mute(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_get_port_index(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_bus_set_port_index(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native String __EXT_JNI__fmod_studio_vca_get_path(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_vca_get_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_vca_set_volume(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_playback_state(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_current_command(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_release(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_command_count(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_length(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_system_object(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_is_valid(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_command_info(ByteBuffer __arg_buffer, double __arg_buffer_length, ByteBuffer __ret_buffer, double __ret_buffer_length);
    public static native String __EXT_JNI__fmod_studio_command_replay_get_command_string(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_command_at_time(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_seek_to_command(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_seek_to_time(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_set_bank_path(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_set_paused(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_start(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_stop(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_get_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_set_user_data(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_set_frame_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_set_create_instance_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
    public static native double __EXT_JNI__fmod_studio_command_replay_set_load_bank_callback(ByteBuffer __arg_buffer, double __arg_buffer_length);
}