
fmod_studio_event_description_release_all_instances(event_guid)

fmod_studio_bank_unload(master_bank_index)
fmod_studio_bank_unload(master_strings_bank_index)
fmod_studio_bank_unload(music_bank_index)
