
fmod_studio_event_description_release_all_instances(AmbienceDescription_guid)
fmod_studio_event_description_release_all_instances(cancel_guid)
fmod_studio_event_description_release_all_instances(explosion_guid)

fmod_studio_bank_unload(master_bank_index)
fmod_studio_bank_unload(master_strings_bank_index)
fmod_studio_bank_unload(sfx_bank_index)
